

CREATE TABLE TB_CLIENTE(
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(150) NOT NULL,
    email VARCHAR2(120) UNIQUE NOT NULL,
    cpf VARCHAR2(11) UNIQUE NOT NULL,
    dt_cadastro DATE,
    ativo CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S', 'N')),
    PRIMARY KEY(id_cliente)
);

CREATE TABLE TB_VENDEDOR(
    id_vendedor NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(150) NOT NULL,
    email VARCHAR2(120) UNIQUE NOT NULL,
    dt_admissao DATE,
    ativo CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S', 'N')),
    PRIMARY KEY(id_vendedor)
);

CREATE TABLE TB_CATEGORIA(
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(50) NOT NULL,
    PRIMARY KEY(id_categoria)
);

CREATE TABLE TB_PRODUTO(
    id_produto NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_categoria NUMBER NOT NULL,
    sku VARCHAR2(30) UNIQUE NOT NULL,
    nome VARCHAR2(120) NOT NULL,
    preco_unit NUMBER(12,2) CHECK (preco_unit > 0) NOT NULL,
    ativo CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S', 'N')),
    dt_cadastro DATE,
    PRIMARY KEY(id_produto),
    FOREIGN KEY(id_categoria) REFERENCES TB_CATEGORIA(id_categoria)
);

CREATE TABLE TB_VENDA(
    id_venda NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_cliente NUMBER NOT NULL,
    id_vendedor NUMBER NOT NULL,
    dt_venda DATE DEFAULT SYSDATE NOT NULL,
    valor_liquido NUMBER(14,2) CHECK (valor_liquido > 0) NOT NULL,
    canal VARCHAR2(20) CHECK (canal IN ('APP', 'SITE', 'LOJA', 'TELEFONE')),
    status VARCHAR2(20) CHECK (status IN ('ABERTA', 'FECHADA', 'CANCELADA')),
    PRIMARY KEY(id_venda),
    FOREIGN KEY(id_cliente) REFERENCES TB_CLIENTE(id_cliente),
    FOREIGN KEY(id_vendedor) REFERENCES TB_VENDEDOR(id_vendedor)
);

CREATE TABLE TB_ITEM_VENDA(
    id_item_venda NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_venda NUMBER NOT NULL,
    id_produto NUMBER NOT NULL,
    quantidade NUMBER CHECK (quantidade > 0) NOT NULL,
    valor_unit NUMBER(12,2) CHECK (valor_unit > 0) NOT NULL,
    percentual_desconto NUMBER(12,2) DEFAULT 0 CHECK (percentual_desconto BETWEEN 0 AND 50) NOT NULL,
    valor_total NUMBER(14,2) CHECK (valor_total > 0) NOT NULL,
    PRIMARY KEY(id_item_venda),
    FOREIGN KEY(id_venda) REFERENCES TB_VENDA(id_venda) ON DELETE CASCADE,
    FOREIGN KEY(id_produto) REFERENCES TB_PRODUTO(id_produto)
);